# .github/workflows/main.yml
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run the script with secrets
        env:
          MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
        run: node assets/js/keys.js
